language: julia
julia:
    - 1.4.2

codecov: true

jobs:
    include:
        - stage: "Documentation"
          julia: 1.4.2
          os: linux
          script:
              - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                Pkg.instantiate()'
              - julia --project=docs/ docs/make.jl
          after_success:
              - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
