name = "Jaynes"
uuid = "a2015381-cef8-4fe1-827c-95a77dd17ccf"
authors = ["McCoy R. Becker <mccoybecker@gmail.com>"]
version = "0.1.13"

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
ZigZagBoomerang = "36347407-b186-4a6a-8c98-4f4567861712"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AbstractMCMC = "2.0"
Distributions = "0.23"
DistributionsAD = "0.6"
Flux = "0.8, 0.11"
IRTools = "0.3"
MCMCChains = "4.0"
MacroTools = "0.5"
Reexport = "0.2"
StatsBase = "0.33"
StatsPlots = "0.14"
ZigZagBoomerang = "0.5"
Zygote = "0.4.20"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
